In [ ]:
import tensorflow as tf
import numpy as np

# 1. Tenserflow Tensors

In [ ]:
tenseer_0D = tf.constant(4)

tensor_1D = tf.constant([1,0,3])

tensor_2D = tf.constant([
                        [1.0,2.7,3.2],
                        [5.1,5.3,6.0],
                        [7.8,8.9,9.0]])

tensor_3D = tf.constant([
        [
            [1,2,3],
            [5,5,6]
        ],

        [
            [2,3,4],
            [5,6,7]
        ],

        [
            [2,3,4],
            [5,6,7]
        ]
    ])

tensor_4D = tf.constant([
         [
             [[1, 2, 3],
             [5, 5, 6]],

             [[2, 3, 4],
             [5, 6, 7]]
        ],


         [
             [[1, 2, 3],
             [5, 5, 6]],

             [[2, 3, 4],
             [5, 6, 7]]
        ],


       [
            [[1, 2, 3],
            [5, 5, 6]],

            [[2, 3, 4],
            [5, 6, 7]]
        ],
        [
            [[1, 2, 3],
            [5, 5, 6]],

            [[2, 3, 4],
            [5, 6, 7]]
        ]])
tenseer_0D.shape,tensor_1D.shape,tensor_2D.shape,tensor_3D.shape,tensor_4D.shape

(TensorShape([]),
 TensorShape([3]),
 TensorShape([3, 3]),
 TensorShape([3, 2, 3]),
 TensorShape([4, 2, 2, 3]))

In [ ]:
# Casting of tensor
casted_1D_tensor = tf.cast(tensor_1D,dtype=tf.bool)
casted_2D_tensor = tf.cast(tensor_2D,dtype=tf.int16)
casted_1D_tensor,casted_2D_tensor

(<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>,
 <tf.Tensor: shape=(3, 3), dtype=int16, numpy=
 array([[1, 2, 3],
        [5, 5, 6],
        [7, 8, 9]], dtype=int16)>)

In [ ]:
# Eye tensor
'''
    args:
        num_rows: number of rows should be non -ve
        num_columns(optional): number of columns should be non negative | defult:None
        batch_shape(optional): 1 list or tuple of python if provided returns tensors with leading batch dimention | defult:None
        dtypes(optional): To givr datatype | defult:None
        name(optional): Provides name to tensor output
    returns: Identity matrix or Matrix in Reduced Row Echolan form
'''

eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[3,2],
    dtype=tf.int16
)
eye_tensor

<tf.Tensor: shape=(3, 2, 3, 4), dtype=int16, numpy=
array([[[[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]],

        [[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]]],


       [[[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]],

        [[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]]],


       [[[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]],

        [[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0]]]], dtype=int16)>

In [ ]:
# fill method
'''
    args:
        dims: 1D sequence to determine the shape of tensor
        value: a unique value to fill the tensor (int or float)
        name(optional): name of the output
        layout(optional)
    returns: a tf.Tensor with shape of provided dims and values
    raises:
        InvalidArgumentError: if dims contains -ve values
        NotfiundError: if dims contains non-integer entries
'''
tf.fill([3,4],0.1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]], dtype=float32)>

In [ ]:
# Indexing of tensor
print(tensor_2D)

tf.Tensor(
[[1.  2.7 3.2]
 [5.1 5.3 6. ]
 [7.8 8.9 9. ]], shape=(3, 3), dtype=float32)


In [ ]:
tensor_2D[::-1,::]

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[7.8, 8.9, 9. ],
       [5.1, 5.3, 6. ],
       [1. , 2.7, 3.2]], dtype=float32)>

# 1.1 Maths

In [ ]:
x = tf.constant([-3,4,-2.5])
y = tf.constant([3+4j,4+6J])
tf.math.abs(x),tf.math.abs(y)


(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3. , 4. , 2.5], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float64, numpy=array([5.        , 7.21110255])>)

In [ ]:
'''
    "+": element wise addition
    "-": element wise subteacrion
    "*": element wise multiplication
    "/": element wise division
    "@": Matrix Multiplication
'''

x1 = tf.constant([2,4,8,1,9])
x2 = tf.constant([5,8,12,5,9])
print(f" '+' : {x1 + x2}")
print(f" '-' : {x1 - x2}")
print(f" '*' : {x1 * x2}")

 '+' : [ 7 12 20  6 18]
 '-' : [-3 -4 -4 -4  0]
 '*' : [10 32 96  5 81]


In [ ]:
x1 = tf.constant([4,6,7,5,9])
x2 = tf.constant([5,3,8,1,9])
print(f"min: {tf.math.minimum(x1,x2)}")
print(f"min: {tf.maximum(x1,x2)}")

min: [4 3 7 1 9]
min: [5 6 8 5 9]


In [ ]:
A = tf.constant([[2, 20, 30, 3, 6],
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(f"axis = 0 : {tf.argmax(A,axis=0)}")
print(f"axis = 1 : {tf.argmax(A,axis=1)}")

axis = 0 : [2 2 0 2 2]
axis = 1 : [2 2 1]


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [2**8,2**16],[3**2,3**3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# Formula for calculating sigmoid(x) = y = 1/(1/exp(-x))
x = tf.constant([-128.0, 0.0, 128.0], dtype=tf.float32)
tf.sigmoid(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

# 1.2 Linear algebra

In [ ]:

# Define a 4x4 matrix
input_matrix = tf.constant([[1, 2, 3, 4],
                            [5, 6, 7, 8],
                            [9,10,11,12],
                            [13,14,15,16]])

# Keep 1 lower diagonal and 1 upper diagonal
result = tf.linalg.band_part(input_matrix, num_lower=0, num_upper=0)

print(result)


tf.Tensor(
[[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0 11  0]
 [ 0  0  0 16]], shape=(4, 4), dtype=int32)


In [ ]:
x = tf.constant([[2, 2],
                [3, 3]])
y = tf.constant([[8, 16],
                 [2, 3]])
print(np.einsum("ij,ij->ij",x,y))

[[16 32]
 [ 6  9]]


In [ ]:
Q = np.random.randn(32,64,512)  #bqm
K = np.random.randn(32,128,512) #bkm
print(np.einsum("bqm,bkm -> bqk", Q,K).shape)

(32, 64, 128)


In [ ]:
X = tf.constant(np.random.randn(1,2,4))
print(tf.expand_dims(X,axis=2))
Y = tf.constant([2,3,4,5])
print(tf.expand_dims(Y,axis=1))
Z = tf.constant([[2,5,9]])
print(tf.squeeze(Z))
print(tf.squeeze(X,axis=0))

tf.Tensor(
[[[[ 0.08686656 -0.10294364 -0.5513401  -0.74147677]]

  [[-0.40544012  0.34224428  0.02239988  0.06485415]]]], shape=(1, 2, 1, 4), dtype=float64)
tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)
tf.Tensor([2 5 9], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0.08686656 -0.10294364 -0.5513401  -0.74147677]
 [-0.40544012  0.34224428  0.02239988  0.06485415]], shape=(2, 4), dtype=float64)
